import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { constructPrompt } from "../agent/prompt";
import { validateTaskDirectory } from "../../validators/validate-task";

/**
 * Harbor export adapter.
 *
 * Converts a bun-bench task package into a Harbor-compatible task package
 * (Terminal-Bench-lineage layout: task.toml + instruction.md + environment/ +
 * tests/ + solution/). Harbor is the primary execution engine; this adapter is
 * the bridge. It does NOT execute agents, suites, or rollout capture — Harbor
 * provides those.
 *
 * Layout produced under <outRoot>/<sanitized-id>/:
 *   task.toml                 Harbor task metadata (documented fields only)
 *   instruction.md            Agent-facing prompt (== bun-bench constructed prompt)
 *   README.md                 Human summary, preserves the true bun-bench id
 *   bun-bench.meta.json       Full bun-bench provenance + scoring (sidecar)
 *   .gitignore
 *   environment/
 *     Dockerfile              Bun runtime; bakes the agent-visible workspace
 *     app/                    Starter workspace copied to /app (agent edits here)
 *   tests/
 *     test.sh                 Verifier: runs public + hidden, writes reward.txt
 *     public/ hidden/ helpers/  Authoritative test assets (runner-only at verify)
 *   solution/
 *     solve.sh                Oracle: writes the reference solution into /app
 */

export type ExportResult = {
  id: string;
  harborName: string;
  outDir: string;
};

const HARBOR_SCHEMA_VERSION = "1.3";
const BUN_IMAGE = "oven/bun:1";
const SOLUTION_HEREDOC = "BUN_BENCH_SOLUTION_EOF";

export async function exportTask(taskDirInput: string, outRoot: string): Promise<ExportResult> {
  const taskDir = resolve(process.cwd(), taskDirInput);

  const validation = await validateTaskDirectory(relativeToCwd(taskDir));
  if (validation.errors.length > 0) {
    throw new Error(
      `cannot export invalid task ${taskDirInput}:\n  - ${validation.errors.join("\n  - ")}`,
    );
  }

  const task = parseTaskYaml(taskDir);
  const id = String(task.id);
  const harborName = `bun-bench/${sanitizeName(id)}`;
  const outDir = resolve(process.cwd(), outRoot, sanitizeName(id));

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(join(outDir, "environment", "app"), { recursive: true });
  mkdirSync(join(outDir, "tests"), { recursive: true });
  mkdirSync(join(outDir, "solution"), { recursive: true });

  writeFileSync(join(outDir, "task.toml"), renderTaskToml(task, harborName));
  writeFileSync(join(outDir, "instruction.md"), constructPrompt(taskDir, task as never));
  writeFileSync(join(outDir, "README.md"), renderReadme(task));
  writeFileSync(join(outDir, "bun-bench.meta.json"), `${JSON.stringify(buildMeta(task), null, 2)}\n`);
  writeFileSync(join(outDir, ".gitignore"), HARBOR_GITIGNORE);

  writeEnvironment(taskDir, outDir);
  writeTests(taskDir, outDir);
  writeSolution(taskDir, outDir);

  return { id, harborName, outDir };
}

// --- environment (agent-visible workspace baked into the image) ---------------

function writeEnvironment(taskDir: string, outDir: string): void {
  const appDir = join(outDir, "environment", "app");

  // The agent-visible workspace: starter source + manifest + lockfile + public
  // tests + helpers. Deliberately excludes task.yaml (carries known_failure_modes
  // and scoring) and hidden tests.
  copyFile(join(taskDir, "package.json"), join(appDir, "package.json"));
  copyDir(join(taskDir, "src"), join(appDir, "src"));
  copyDir(join(taskDir, "tests", "public"), join(appDir, "tests", "public"));
  copyDir(join(taskDir, "tests", "helpers"), join(appDir, "tests", "helpers"));
  copyLockfile(taskDir, appDir);
  copyPublicFixtures(taskDir, appDir);

  writeFileSync(join(outDir, "environment", "Dockerfile"), renderDockerfile());
}

function renderDockerfile(): string {
  return `# Generated by bun-bench Harbor export adapter.
FROM ${BUN_IMAGE}

WORKDIR /app

# Bake the agent-visible starter workspace. The agent edits files under /app.
COPY app/ /app/
`;
}

// --- tests (authoritative verifier assets, runner-only at verify time) --------

function writeTests(taskDir: string, outDir: string): void {
  const testsDir = join(outDir, "tests");
  copyDir(join(taskDir, "tests", "public"), join(testsDir, "public"));
  copyDir(join(taskDir, "tests", "hidden"), join(testsDir, "hidden"));
  copyDir(join(taskDir, "tests", "helpers"), join(testsDir, "helpers"));
  writeFileSync(join(testsDir, "test.sh"), renderTestSh());
}

function renderTestSh(): string {
  // Runs from /tests against the agent solution at /app, mirroring the bun-bench
  // local lifecycle: public and hidden suites both spawn the solution's server
  // via the helper (BUN_BENCH_APP_DIR=/app). Reward uses the bun-bench gate model:
  //   public pass + hidden pass -> 1.0
  //   public pass + hidden fail -> 0.25
  //   public fail               -> 0.0
  return `#!/usr/bin/env bash
# Generated by bun-bench Harbor export adapter. Authoritative verifier.
set -uo pipefail

mkdir -p /logs/verifier
cd /tests
export BUN_BENCH_APP_DIR=/app

bun test public > /logs/verifier/public.log 2>&1
PUBLIC_EXIT=$?
bun test hidden > /logs/verifier/hidden.log 2>&1
HIDDEN_EXIT=$?

if [ "$PUBLIC_EXIT" -eq 0 ] && [ "$HIDDEN_EXIT" -eq 0 ]; then
  REWARD=1.0
elif [ "$PUBLIC_EXIT" -eq 0 ]; then
  REWARD=0.25
else
  REWARD=0.0
fi

echo "$REWARD" > /logs/verifier/reward.txt
echo "bun-bench verifier: public_exit=$PUBLIC_EXIT hidden_exit=$HIDDEN_EXIT reward=$REWARD"

# Exit non-zero unless fully correct so Harbor's pass/fail aligns with reward 1.0.
[ "$REWARD" = "1.0" ]
`;
}

// --- solution (oracle: materializes the reference solution into /app) ---------

function writeSolution(taskDir: string, outDir: string): void {
  const referenceSrc = join(taskDir, "solutions", "reference", "src");
  const files = listFilesRecursive(referenceSrc).map((absolute) => ({
    rel: relative(referenceSrc, absolute).split("\\").join("/"),
    content: readFileSync(absolute, "utf8"),
  }));

  if (files.length === 0) {
    throw new Error(`reference solution has no files under solutions/reference/src for ${taskDir}`);
  }

  writeFileSync(join(outDir, "solution", "solve.sh"), renderSolveSh(files));
}

function renderSolveSh(files: Array<{ rel: string; content: string }>): string {
  const blocks = files.map((file) => {
    const dir = file.rel.includes("/") ? file.rel.slice(0, file.rel.lastIndexOf("/")) : "";
    const mkdir = dir ? `mkdir -p /app/src/${dir}\n` : "";
    // Quoted heredoc delimiter => no shell expansion of the embedded source.
    return `${mkdir}cat > /app/src/${file.rel} <<'${SOLUTION_HEREDOC}'\n${file.content.replace(/\n?$/, "\n")}${SOLUTION_HEREDOC}\n`;
  });

  return `#!/usr/bin/env bash
# Generated by bun-bench Harbor export adapter. Oracle reference solution.
# Overwrites the starter source under /app with the bun-bench reference.
set -euo pipefail

mkdir -p /app/src
${blocks.join("\n")}`;
}

// --- task.toml ----------------------------------------------------------------

function renderTaskToml(task: Record<string, unknown>, harborName: string): string {
  const description = String(task.description ?? task.title ?? "").replace(/\s+/g, " ").trim();
  const difficulty = task.difficulty as { level?: number } | undefined;
  const level = typeof difficulty?.level === "number" ? difficulty.level : undefined;
  const category = String(task.category ?? "");
  const tags = Array.isArray(task.tags) ? task.tags.map(String) : [];
  const timeouts = (task.timeouts ?? {}) as Record<string, number>;
  const environment = (task.environment ?? {}) as Record<string, unknown>;
  const network = String(environment.network ?? "disabled");

  // Provenance preserved inside task.toml via free-form keywords (Harbor-safe),
  // and in full in bun-bench.meta.json.
  const keywords = [
    "bun-bench",
    `id:${task.id}`,
    `task_version:${task.task_version}`,
    `spec_version:${task.spec_version}`,
    `category:${category}`,
    level !== undefined ? `difficulty:${level}` : undefined,
  ].filter((value): value is string => typeof value === "string");

  const verifierTimeout = Math.max(300, Number(timeouts.test_seconds ?? 120) * 2 + 60);
  const agentTimeout = Number(timeouts.total_seconds ?? 900);
  const buildTimeout = Math.max(600, Number(timeouts.install_seconds ?? 120));

  return `schema_version = "${HARBOR_SCHEMA_VERSION}"
artifacts = []

[task]
name = "${harborName}"
description = ${tomlString(description)}
keywords = ${tomlStringArray(keywords)}
[[task.authors]]
name = "tincomputer.ai"

[metadata]
author_name = "tincomputer.ai"
author_email = "unknown"
difficulty = "${harborDifficulty(level)}"
category = "software_engineering"
tags = ${tomlStringArray([...new Set([category, ...tags].filter(Boolean))])}
expert_time_estimate_min = 0.0
junior_time_estimate_min = 0.0

[verifier]
timeout_sec = ${verifierTimeout.toFixed(1)}

[verifier.env]

[agent]
timeout_sec = ${agentTimeout.toFixed(1)}

[environment]
network_mode = "${network === "disabled" ? "no-network" : "public"}"
build_timeout_sec = ${buildTimeout.toFixed(1)}
os = "linux"
mcp_servers = []

[environment.env]

[solution.env]
`;
}

function buildMeta(task: Record<string, unknown>): Record<string, unknown> {
  return {
    bun_bench_id: task.id,
    task_version: task.task_version,
    spec_version: task.spec_version,
    title: task.title,
    category: task.category,
    difficulty: task.difficulty,
    tags: task.tags,
    scoring: task.scoring,
    success_criteria: task.success_criteria,
    environment_network: (task.environment as Record<string, unknown> | undefined)?.network,
    reward_model: {
      description: "Harbor reward.txt is computed by the bun-bench gate model in tests/test.sh.",
      values: { public_and_hidden_pass: 1.0, public_pass_hidden_fail: 0.25, public_fail: 0.0 },
      maps_to_bun_bench_score: { "1.0": 100, "0.25": 25, "0.0": 0 },
    },
  };
}

function renderReadme(task: Record<string, unknown>): string {
  return `# ${task.title ?? task.id}

Exported bun-bench task for Harbor execution.

- bun-bench id: \`${task.id}\`
- task_version: \`${task.task_version}\`
- spec_version: \`${task.spec_version}\`
- category: \`${task.category}\`

See \`bun-bench.meta.json\` for full provenance and the scoring/reward model.
Generated by the bun-bench Harbor export adapter; do not edit by hand.
`;
}

// --- helpers ------------------------------------------------------------------

function harborDifficulty(level: number | undefined): string {
  if (level === undefined) return "unknown";
  if (level <= 2) return "easy";
  if (level === 3) return "medium";
  return "hard";
}

export function sanitizeName(id: string): string {
  return id
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function parseTaskYaml(taskDir: string): Record<string, unknown> {
  const raw = readFileSync(join(taskDir, "task.yaml"), "utf8");
  return Bun.YAML.parse(raw) as Record<string, unknown>;
}

function copyLockfile(taskDir: string, appDir: string): void {
  for (const lockfile of ["bun.lock", "bun.lockb"]) {
    const source = join(taskDir, lockfile);
    if (existsSync(source)) {
      copyFile(source, join(appDir, lockfile));
      return;
    }
  }
}

function copyPublicFixtures(taskDir: string, appDir: string): void {
  const publicFixtures = join(taskDir, "fixtures", "public");
  if (existsSync(publicFixtures)) {
    copyDir(publicFixtures, join(appDir, "fixtures", "public"));
    return;
  }
  const fixturesDir = join(taskDir, "fixtures");
  if (!existsSync(fixturesDir)) return;
  const hasRealFiles = readdirSync(fixturesDir).some((entry) => entry !== ".gitkeep");
  if (hasRealFiles) {
    copyDir(fixturesDir, join(appDir, "fixtures"));
  }
}

function listFilesRecursive(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...listFilesRecursive(full));
    } else {
      out.push(full);
    }
  }
  return out;
}

function copyFile(source: string, destination: string): void {
  if (!existsSync(source)) return;
  mkdirSync(resolve(destination, ".."), { recursive: true });
  cpSync(source, destination);
}

function copyDir(source: string, destination: string): void {
  if (!existsSync(source)) {
    throw new Error(`missing directory: ${source}`);
  }
  cpSync(source, destination, { recursive: true });
}

function relativeToCwd(absolutePath: string): string {
  const cwd = process.cwd();
  return absolutePath.startsWith(`${cwd}/`) ? absolutePath.slice(cwd.length + 1) : absolutePath;
}

function tomlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function tomlStringArray(values: string[]): string {
  if (values.length === 0) return "[]";
  return `[${values.map(tomlString).join(", ")}]`;
}

const HARBOR_GITIGNORE = `# Git
.git/

# OS
.DS_Store

# Harbor
dist.tar.gz
`;
